name: Validate Codeowners

on:
  push:
    branches:
      - main


jobs:
  validate_codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Codeowners file
        uses: mszostok/codeowners-validator@v0.7.4 
        with:
          checks: "files,owners"
