name: Validate Codeowners

on:
  push:



jobs:
  validate_codeowners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate Codeowners file
        uses: mszostok/codeowners-validator@v0.7.4 
        with:
          
          github_access_token: "${{ secrets.ACCESS_TOKEN }}"
          checks: "files,owners"
