name: Validate Workflows Run 
on:
  push:

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List .yaml and .yml files in .github/workflows directory
        id: get_files
        run: |
          echo "::set-output name=workflow_files::$(ls .github/workflows/*.{yaml,yml})"

      - name: Check if workflows have pull_request trigger
        id: check_pull_request
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.get_files.outputs.workflow_files }}"
          for file in "${files[@]}"; do
            if [ $(yq e '.on.pull_request' $file) != "null" ]; then
              echo "Workflow $file is triggered by pull requests"
              echo "::set-output name=has_pull_request::true"
              exit 0
            fi
          done
          echo "No workflow is triggered by pull requests"
          echo "::set-output name=has_pull_request::false"
          exit 1
