name: Validate Workflows Run on Pull Request comment


on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List .yaml and .yml files in .github/workflows directory
        id: get_files
        run: |
          echo "::set-output name=workflow_files::$(ls .github/workflows/*.{yaml,yml} | tr '\n' ' ')"
          echo "${{ steps.get_files.outputs.workflow_files }}"

      - name: Get PR Number
        id: pr
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}" 
          echo "::set-output name=number::${{ github.event.pull_request.number }}"

#       - name: Create comment
#         uses: peter-evans/create-or-update-comment@v3
#         with:
#           issue-number: 2
#           body: |
#             This is a multi-line test comment
#             - With GitHub **Markdown** :sparkles:
#             - Created by [create-or-update-comment][1]

#             [1]: https://github.com/peter-evans/create-or-update-comment
#           reactions: '+1'

          
          
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          echo "${{ steps.pr.outputs.number }}"

      - name: Check if workflows have pull_request trigger
        id: check_pull_request
        run: |
          echo  "${{ steps.pr_number.outputs.pr }}"
          IFS=' ' read -r -a files <<< "${{ steps.get_files.outputs.workflow_files }}"
          FOUND_PR_WORKFLOW=false
          for file in "${files[@]}"; do
            ON_SECTION=$(yq e '.on' $file)
            if [[ $ON_SECTION == *"pull_request"* ]]; then
              FOUND_PR_WORKFLOW=true
              echo "Workflow $file is triggered by pull requests"
              break
            fi
          done
          if [[ $FOUND_PR_WORKFLOW == false ]]; then
            echo "No workflow is triggered by pull requests"
            exit 0
          fi
          
