name: List YAML Files

on:
  push:

jobs:
  list_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List .yaml and .yml files in .github/workflows directory
        id: get_files
        run: |
          echo "::set-output name=workflow_files::$(echo $(ls .github/workflows/*.y{a,}ml))"

      - name: Print file list
        run: echo "${{ steps.get_files.outputs.workflow_files }}"
