name: Get PR Number

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print_pr_number:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Number
        run: echo "PR Number: ${{ github.event.pull_request.number }}"
