name: Validate Workflows Run 

on:
  push:

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List .yaml and .yml files in .github/workflows directory
        id: get_files
        run: |
          echo "::set-output name=workflow_files::$(ls .github/workflows/*.{yaml,yml} | tr '\n' ' ')"

      - name: Check if workflows have pull_request trigger
        id: check_pull_request
        run: |
          IFS=' ' read -r -a files <<< "${{ steps.get_files.outputs.workflow_files }}"
          FOUND_PR_WORKFLOW=false
          for file in "${files[@]}"; do
            TRIGGER=$(yq e '.on.pull_request' $file)
            if [[ "$TRIGGER" != "null" ]]; then
              FOUND_PR_WORKFLOW=true
              echo "Workflow $file is triggered by pull requests"
              break
            fi
          done
          echo "$FOUND_PR_WORKFLOW" > pr_workflow_check.txt

      - name: Fail if no workflow triggers on pull_request
        uses: mikefarah/yq@master
        id: final_check
        with:
          cmd: yq eval pr_workflow_check.txt
        run: |
          if [[ "${{ steps.final_check.outputs.result }}" == "false" ]]; then
            echo "No workflow is triggered by pull requests"
            exit 1
          fi
