name: Validate Workflows Run on Pull Request comment


on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get workflow file path
        run: |
          echo "::set-output name=path::.github/workflows/${{ github.workflow }}.yml"
        id: workflow
      - name: Print workflow file path
        run: |
          echo "${{ steps.workflow.outputs.path }}"
      