name: Workflow Failure Monitor

on:
  workflow_run:
    workflows: ["Validate Codeowners"]
    types:
      - completed 



jobs:
  check_and_rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Check Count
      id: count
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |
          const workflow_id = ${{ github.event.workflow_run.workflow_id }}; // Use GitHub Actions expression here
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const result = await github.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs', {
            owner: owner,
            repo: repo,
            workflow_id: workflow_id
          })
          console.log(result);
          const run_id = result.data.workflow_runs[0].id; // Assuming the first run is the one you want
          const run_attempts = result.data.workflow_runs.find(run => run.id === run_id).run_attempt;
          console.log(run_attempts);
          core.setOutput('run_attempts', run_attempts);
       
    - name: Rerun Workflow
      if: ${{ github.event.workflow_run.conclusion == 'failure'   && steps.count.outputs.run_attempts < 2}}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |   
          const run_id = "${{ github.event.workflow_run.id }}"
          const result = await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run_id
          })
          console.log(result)
