name: Workflow Failure Monitor

on:
  workflow_run:
    workflows: ["Validate Codeowners"]
    types:
      - completed 



jobs:
  check_and_rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    # - name: Check run count
    #   id: check
    #   run: echo "::set-output name=count::$(gh run list -w 'Your Workflow ID' --json status | jq '[.runs[] | select(.status=="completed" and .conclusion=="failure")] | length')"
    # - name: Check Count
    #   if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    #   uses: actions/github-script@v5
    #   with:
    #     github-token: ${{ secrets.ACCESS_TOKEN }}
    #     script: |
    #       # const workflow_id = "${{ github.event.workflow_run.workflow_id }}"
    #       # const result = await github.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs', {
    #       #   owner: context.repo.owner,
    #       #   repo: context.repo.repo,
    #       #   workflow_id: "61472218"
    #       # })
    #       # console.log(result)
    #       # # const run_attempts = result.data.workflow_runs.find(run => run.id === run_id).run_attempt
    #       # # echo $run_attempts
    #       echo "Test"
       
    - name: Rerun Workflow
      if: ${{ github.event.workflow_run.conclusion == 'failure' }}
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        script: |   
          const run_id = "${{ github.event.workflow_run.id }}"
          const result = await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run_id
          })
          console.log(result)
    # - name: Rerun Workflow 
    #       if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    #       uses: actions/github-script@v5
    #       with:
    #         github-token: ${{ secrets.ACCESS_TOKEN }}
    #         script: |
    #           const run_id = "${{ github.event.workflow_run.id }}"
    #           const workflow_id = "${{ github.event.workflow_run.workflow_id }}"
    #           const result = await github.request('GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs', {
    #             owner: context.repo.owner,
    #             repo: context.repo.repo,
    #             workflow_id: workflow_id
    #           })
    #           const run_attempts = result.data.workflow_runs.find(run => run.id === run_id).run_attempt
    #           if (run_attempts < 2) {
    #             await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
    #               owner: context.repo.owner,
    #               repo: context.repo.repo,
    #               run_id: run_id
    #             })
    #             console.log(`Workflow run rerun initiated. This is attempt number ${run_attempts + 1}.`)
    #           } else {
    #             console.log(`Workflow run has already been rerun ${run_attempts} times. Not rerunning again.`)
    #           }