name: Workflow Failure Monitor

on:
  workflow_run:
    workflows: ["Validate Codeowners"]
    types:
      - completed 



jobs:
  check_and_rerun:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
    steps:
    - name: Check run count
      id: check
      run: echo "::set-output name=count::$(gh run list -w 'Your Workflow ID' --json status | jq '[.runs[] | select(.status=="completed" and .conclusion=="failure")] | length')"

    - name: Rerun workflow
      uses: actions/github-script@v5
      if: ${{ steps.check.outputs.count < 3 }}
      with:
        script: |
          const run_id = "${{ github.event.workflow_run.id }}"
          const result = await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run_id
          })
