name: Validate Workflows

on:
  push:
    branches:
      - main

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Check workflows for pull_request trigger
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
          
          WORKFLOW_FILES=$(ls .github/workflows/*.yaml)
          FOUND_PR_WORKFLOW=false
          
          for FILE in $WORKFLOW_FILES; do
            ON_SECTION=$(yq e '.on' $FILE)
            if [[ $ON_SECTION == *"pull_request"* ]]; then
              FOUND_PR_WORKFLOW=true
              echo "Workflow $FILE is triggered by pull requests"
              break
            fi
          done
          
          if [[ $FOUND_PR_WORKFLOW == false ]]; then
            echo "No workflow is triggered by pull requests"
            exit 1
          fi
