name: Validate Workflows

on:
  push:
    branches:
      - main

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install JQ
        run: sudo apt-get install jq
      - name: Check workflows for pull_request trigger
        run: |
          OWNER=$(echo "${{ github.repository }}" | cut -d / -f 1)
          REPO=$(echo "${{ github.repository }}" | cut -d / -f 2)
          WORKFLOW_FILES=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -s "https://api.github.com/repos/$OWNER/$REPO/contents/.github/workflows" | jq -r '.[].name')
          FOUND_PR_WORKFLOW=false
          for FILE in $WORKFLOW_FILES; do
            FILE_CONTENT=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                                -s "https://api.github.com/repos/$OWNER/$REPO/contents/.github/workflows/$FILE" | jq -r '.content' | base64 --decode)
            if [[ $FILE_CONTENT == *"pull_request"* ]]; then
              FOUND_PR_WORKFLOW=true
              echo "Workflow $FILE is triggered by pull requests"
              break
            fi
          done
          if [[ $FOUND_PR_WORKFLOW == false ]]; then
            echo "No workflow is triggered by pull requests"
            exit 1
          fi
