name: Validate Workflows Run on Pull Request

on:
  push:
    branches:
      - main

jobs:
  check_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Check workflows for pull_request trigger
        run: |
          WORKFLOW_FILES=$(ls .github/workflows/*.{yaml,yml})
          FOUND_PR_WORKFLOW=false

          for FILE in $WORKFLOW_FILES; do
            - name: Check for pull_request trigger in $FILE
              id: check_pull_request_trigger
              uses: mikefarah/yq@master
              with:
                cmd: yq e '.on.pull_request' $FILE

            - name: Check result and update FOUND_PR_WORKFLOW if necessary
              run: |
                if [[ "${{ steps.check_pull_request_trigger.outputs.result }}" != "null" ]]; then
                  FOUND_PR_WORKFLOW=true
                  echo "Workflow $FILE is triggered by pull requests"
                  break
                fi

          if [[ $FOUND_PR_WORKFLOW == false ]]; then
            echo "No workflow is triggered by pull requests"
            exit 1
          fi
